-- DROP TABLE Users;
-- DROP TABLE Tests;
-- DROP TABLE Questions;
-- DROP TABLE Answers;

CREATE TABLE IF NOT EXISTS Users (
    User TEXT NOT NULL,
    Id INTEGER NOT NULL,
    Available INTEGER DEFAULT(1)
);

CREATE TABLE IF NOT EXISTS Tests (
    UserId INTEGER NOT NULL,
    Uid TEXT NOT NULL,
    StartTime DATETIME DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW', 'LOCALTIME')),
    Questions TEXT NOT NULL,
    Active INTEGER NOT NULL DEFAULT 1,
    Result REAL DEFAULT -1;
    FOREIGN KEY(UserId) REFERENCES Users(Id)
);

CREATE TABLE IF NOT EXISTS Questions (
    Id INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    Question TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Answers (
    Id INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
    QId INTEGER NOT NULL,
    Answer TEXT NOT NULL,
    Correct INTEGER NOT NULL DEFAULT NULL,
    FOREIGN KEY(QId) REFERENCES Questions(Id)
);
